name: Lint

on:
  push:
    branches: [master]
  pull_request:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Conda Environment
        uses: goanpeca/setup-miniconda@v1
        env:
          # https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          miniconda-version: latest
          auto-update-conda: true
          python-version: 3.9
          environment-file: ci/requirements-lint.yml
          activate-environment: xarray_mongodb-lint
          auto-activate-base: false

      - name: conda info
        shell: bash -l {0}
        run: conda info

      - name: conda list
        shell: bash -l {0}
        run: conda list

      - name: flake8
        shell: bash -l {0}
        run: flake8

      - name: black version
        shell: bash -l {0}
        run: black --version

      - name: black
        shell: bash -l {0}
        run: black --check -t py37 -v .

      - name: isort
        shell: bash -l {0}
        run: isort --check --py 37 .

      - name: mypy
        shell: bash -l {0}
        run: mypy --python-version 3.7 --install-types --non-interactive --ignore-missing-imports --exclude 'doc/conf\.py$' .
